### PR TITLE
Fix automatic formatting for #include <cmocka.h> in tests

### PR DESCRIPTION
**Pull request by prajnoha**
`#include <cmocka.h>` in tests needs to go at the very end - looks like cmocka doesn't include its own dependencies.

### CODE REVIEW

**Comment by trgill** [comment]
@prajnoha the Jenkins failure is due to a build problem on rawhide with multipath.  I was working on enabling that when I ran into the cmocka issue.  This PR passed the tests on F33 and Centos Stream.   I think it is good to merge. :+1:

**Comment by trgill** [comment]
retest this please

Note: This is a command to Jenkins to restart the tests.

**Comment by trgill** [comment]
retest this please

**Comment by trgill** [comment]
Jenkins is building rawhide with multipath enabled now. :+1:

**Comment by prajnoha** [comment]
👍🏼

**Pull request merged**
