### PR TITLE
Fix variable alignment issues.

### PR DESCRIPTION
**Pull request by bmarzins**
These are all the alignment issues I found while looking through the code.

### CODE REVIEW

**Comment by prajnoha** [comment]
Thanks! I just have one question about this part:

```
struct kv_store_value {
  ...
  char                       data[] __attribute__((aligned));
};
```

Will compiler deduce we need pointer alignment or do we need to state that directly with `aligned(sizeof(intpr_t))` or so?

**Comment by bmarzins** [comment]
> Thanks! I just have one question about this part:
> 
> ```
> struct kv_store_value {
>   ...
>   char                       data[] __attribute__((aligned));
> };
> ```
> 
> Will compiler deduce (from the `[]`) we need pointer alignment or do we need to state that directly with `aligned(sizeof(intpr_t))` or so?

You need that `__attribute__((aligned))` to tell the compiler that data needs to start at pointer alignment. Otherwise, since it's an array of chars, it just needs char alignment, which means it can start anywhere.
```
[bmarzins@octiron putzing]$ cat align.c
#include <stddef.h>
#include <stdio.h>

struct test {
	short int pad;
	char data[];
};

struct aligned_test {
	short int pad;
	char data[] __attribute__((aligned));
};

int main(void)
{
	printf("test data offset: %lu\n", offsetof(struct test, data));
	printf("aligned test data offset: %lu\n", offsetof(struct aligned_test, data));
	return 0;
}	
[bmarzins@octiron putzing]$ ./align 
test data offset: 2
aligned test data offset: 16
```

**Comment by bmarzins** [comment]
So `__attribute__((aligned))` is supposed to give the maximum useful alignment for your system.  I don't know why it gave me a 16 byte alignment instead of an 8 byte one (dunno what could possibly need more than 8 byte alignment on a 64 bit system), but replacing it with `__attribute__((aligned (sizeof(intptr_t))))` gives me the expected pointer alignment

```
test data offset: 2
aligned test data offset: 8
```
I can change that and update the MR if you want.

**Comment by prajnoha** [comment]
> So `__attribute__((aligned))` is supposed to give the maximum useful alignment for your system. I don't know why it gave me a 16 byte alignment instead of an 8 byte one (dunno what could possibly need more than 8 byte alignment on a 64 bit system)

Hmm, maybe some specialized CPU registers are taken into account (the 128-bit vector ones/SSE...)? Just guessing...

> I can change that and update the MR if you want.

...that's OK, let's keep what compiler think is the best for the architecture. Will merge then. Thanks!

**Pull request merged**
