### PR TITLE
sidctl: add json output for dump and version commands

### PR DESCRIPTION
**Pull request by trgill**
Note: also updated .gitignore with .vscode

The PR is the minimum to get JSON output for sidctl dump and version commands.

Example output for dump:

```
# sidctl dump -j
{
    "siddb": [
        {
            "RECORD": 0,
            "key": ":U:::::ID_FS_BOOT_SYSTEM_ID",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 1,
            "key": ":U:::::ID_FS_UUID_SUB_ENC",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 2,
            "key": ":U:::::ID_FS_LABEL_ENC",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 3,
            "key": ":U:::::ID_FS_UUID_SUB",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 4,
            "key": ":U:::::ID_PART_TABLE_UUID",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 5,
            "key": ":U:::::ID_FS_UUID_ENC",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 6,
            "key": ":U:::::ID_FS_LABEL",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 7,
            "key": ":U:::::ID_FS_VERSION",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 8,
            "key": ":U:::::ID_FS_PUBLISHER_ID",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 9,
            "key": ":U:::::ID_PART_ENTRY_NAME",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 10,
            "key": ":U:::::ID_PART_TABLE_TYPE",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 11,
            "key": ":D:::::SID_NEXT_MOD",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 12,
            "key": ":U:::::ID_FS_APPLICATION_ID",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 13,
            "key": ":U:::::ID_FS_USAGE",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 14,
            "key": ":U:::::ID_FS_UUID",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 15,
            "key": ":U:::::ID_FS_TYPE",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 16,
            "key": ":U:::::ID_FS_SYSTEM_ID",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 17,
            "key": ":U:::::ID_PART_ENTRY_TYPE",
            "seqnum": 0,
            "KV_MOD_RESERVED": true,
            "owner": "block/blkid",
            "value": ""
        },
        {
            "RECORD": 18,
            "key": ":U:(null)::::SID_SESSION_ID",
            "seqnum": 0,
            "KV_PERSISTENT": true,
            "owner": "#core",
            "value": "597e2645-90ff-45e1-a618-ace103b9b88b"
        }
    ]
}

```

Example output for version:

```
# sidctl version -j
{
    "KEY_SIDCTL_PROTOCOL": 1,
    "KEY_SIDCTL_MAJOR": 0,
    "KEY_SIDCTL_MINOR": 0,
    "KEY_SIDCTL_RELEASE": 4,
    "KEY_SID_PROTOCOL": 1,
    "KEY_SID_MAJOR": 0,
    "KEY_SID_MINOR": 0,
    "KEY_SID_RELEASE": 4
}
```

### CODE REVIEW

**Comment by trgill** [comment]
@prajnoha 

I'm not sure about these changes.  There are several open source C JSON libraries - but I was reluctant to introduce the dependency when we only need to write JSON.

I think this could be done with less code using macros - but I wasn't able to keep things simple using a macro - so I just implemented several small functions.

**Review by prajnoha — COMMENTED** [review]
I think we don't need to use external library for formatting JSON - looks just fine as you implemented it. If we ever needed anything more (like support for input in JSON), we could switch to using an external library, but even in that case it's questionable whether it would be needed. So I'm fine with these small helper functions....

Just a few things:

 - there's a small glitch with array reporting (this example is for the layering record where we have 2 LVM LVs 253:0 and 253:1 on top of a base device 252:3); there's "values" oddly formatted/indented:
```
    {
            "RECORD": 58,
            "key": ":D:252_3:LYR:::#GIN",
            "seqnum": 4505,
            "KV_MOD_PRIVATE": true,
            "KV_MOD_RESERVED": true,
            "owner": "#core",
            "values
": [
            "values": [
            ":D:253_0:LYR::",
            ]
            "values": [
            ":D:253_1:LYR::",
            ]
        },
```

The original non-JSON output for this is:

```
RECORD: 58
key: :D:252_3:LYR:::#GIN
seqnum: 5170
KV_MOD_PRIVATE
KV_MOD_RESERVED
owner: #core
:D:253_0:LYR::
:D:253_1:LYR::
```

 - we could probably put the flags (the `KV_*`) under its own subsection or array so they're all "together" - with JSON GUI viewers, that would be nicely clickable for collapse/expand

 - I'm thinking whether to use '-j|--json' on command line or if it wouldn't be better to use something like "--format json" so we could add more in the future like "--format yaml" or whatever...

Otherwise, looks good. Thanks!

**Review by prajnoha — COMMENTED** [review]
With `clang`, I'm also seeing these, but haven't looked deeper yet what exactly it means:

```
  CC       sidctl.o
sidctl.c:136:10: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
                printf(field_name);
                       ^~~~~~~~~~
sidctl.c:136:10: note: treat the string as an argument to avoid this
                printf(field_name);
                       ^
                       "%s", 
sidctl.c:153:10: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
                printf(field_name);
                       ^~~~~~~~~~
sidctl.c:153:10: note: treat the string as an argument to avoid this
                printf(field_name);
                       ^
                       "%s", 
sidctl.c:165:18: warning: data argument not used by format string [-Wformat-extra-args]
                printf(PRIu64, value);
                       ~~~~~~  ^
sidctl.c:170:10: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
                printf(field_name);
                       ^~~~~~~~~~
sidctl.c:170:10: note: treat the string as an argument to avoid this
                printf(field_name);
                       ^
                       "%s", 
sidctl.c:172:18: warning: data argument not used by format string [-Wformat-extra-args]
                printf(PRIu64, value);
                       ~~~~~~  ^
sidctl.c:190:11: warning: format string is not a string literal (potentially insecure) [-Wformat-security]
                        printf(field_name);
                               ^~~~~~~~~~
sidctl.c:190:11: note: treat the string as an argument to avoid this
                        printf(field_name);
                               ^
                               "%s", 
6 warnings generated.
```

**Comment by trgill** [comment]
Thanks for the feedback.  Will fix. :+1:

**Comment by trgill** [comment]
@prajnoha should I update Jenkins to run:

`make CC=clang`

as part of PR tests?

**Comment by prajnoha** [comment]
> @prajnoha should I update Jenkins to run:
> `make CC=clang`
> as part of PR tests?

...ehm, up to you :) I'm using clang because I felt it could report more issues than gcc, but on the other hand, gcc is usually the official compiler used to build packages (...and I've also come across things that gcc reported, but not clang - but most of the time it was really clang that reported more to avoid future issues). So I'm more leaned to clang...

**Comment by prajnoha** [comment]
...the clang also has `scan-build` included in `clang-analyzer` package that I was also using for more in-depth code analysis - similar to coverity.  But I haven't run it for a while, I have to admit. This is actually the whole command line I'm using for scan-build:

https://github.com/sid-project/sid/blob/27ee0f69dccb6dfdf37fccc9bef3fd9f425e0493/debug/scan-build.args#L1

**Comment by trgill** [comment]
> > @prajnoha should I update Jenkins to run:

> 
> ...ehm, up to you :) I'm using clang because I felt it could report more issues than gcc, but on the other hand, gcc is usually the official compiler used to build packages (...and I've also come across things that gcc reported, but not clang - but most of the time it was really clang that reported more to avoid future issues). So I'm more leaned to clang...

I added it.  I'll have a look at the scan-build too.

**Comment by trgill** [comment]
Note: CI failure was because clang wasn't installed on the Centos Stream systems.  That has been fixed.

The latest push fixed the bug.
Fixed the clang warnings.
Updated "flags" to a boolean array.
"values" is always an array - even if it only has one value.
Validated the JSON with : https://jsonlint.com/

```
{
    "siddb": [
        {
            "RECORD": 0,
            "key": ":D:253_0:LYR:::#GIN",
            "seqnum": 3110,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:253_4:LYR::"
            ]
        },
        {
            "RECORD": 1,
            "key": ":U:::::ID_FS_BOOT_SYSTEM_ID",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 2,
            "key": ":D:253_2::::#RDY",
            "seqnum": 3105,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 3,
            "key": ":D:253_0:LYR:::#GMB",
            "seqnum": 3098,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:8_0:LYR::"
            ]
        },
        {
            "RECORD": 4,
            "key": ":U:::::ID_FS_UUID_SUB_ENC",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 5,
            "key": ":U:::::ID_FS_LABEL_ENC",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 6,
            "key": ":D:253_3::::#RES",
            "seqnum": 3108,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 7,
            "key": ":D:8_16:LYR:::#GIN",
            "seqnum": 3107,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:253_2:LYR::",
                ":D:253_3:LYR::"
            ]
        },
        {
            "RECORD": 8,
            "key": ":U:::::ID_FS_UUID_SUB",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 9,
            "key": ":U:::::ID_PART_TABLE_UUID",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 10,
            "key": ":D:253_4::::#RES",
            "seqnum": 3112,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 11,
            "key": ":D:253_1::::#RDY",
            "seqnum": 3102,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 12,
            "key": ":U:::::ID_FS_UUID_ENC",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 13,
            "key": ":U:::::ID_FS_LABEL",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 14,
            "key": ":D:253_4:LYR:::#GMB",
            "seqnum": 3110,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:253_0:LYR::",
                ":D:253_1:LYR::",
                ":D:253_2:LYR::",
                ":D:253_3:LYR::"
            ]
        },
        {
            "RECORD": 15,
            "key": ":D:253_2:LYR:::#GIN",
            "seqnum": 3110,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:253_4:LYR::"
            ]
        },
        {
            "RECORD": 16,
            "key": ":D:253_2:LYR:::#GMB",
            "seqnum": 3104,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:8_16:LYR::"
            ]
        },
        {
            "RECORD": 17,
            "key": ":D:253_1::::#MOD",
            "seqnum": 3102,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                "device_mapper"
            ]
        },
        {
            "RECORD": 18,
            "key": ":U:::::ID_FS_VERSION",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 19,
            "key": ":U:::::ID_FS_PUBLISHER_ID",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 20,
            "key": ":D:253_2::::#MOD",
            "seqnum": 3105,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                "device_mapper"
            ]
        },
        {
            "RECORD": 21,
            "key": ":D:253_0::::#RES",
            "seqnum": 3099,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 22,
            "key": ":U:::::ID_PART_ENTRY_NAME",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 23,
            "key": ":D:253_1:LYR:::#GMB",
            "seqnum": 3101,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:8_0:LYR::"
            ]
        },
        {
            "RECORD": 24,
            "key": ":D:253_1:LYR:::#GIN",
            "seqnum": 3110,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:253_4:LYR::"
            ]
        },
        {
            "RECORD": 25,
            "key": ":U:::::ID_PART_TABLE_TYPE",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 26,
            "key": ":D:::::SID_NEXT_MOD",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 27,
            "key": ":D:8_16::::#RDY",
            "seqnum": 3114,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 28,
            "key": ":D:8_16:USR:::SID_NEXT_MOD",
            "seqnum": 3114,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": true},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": false}
            ],
            "owner": "block/blkid",
            "values": [
                "dm"
            ]
        },
        {
            "RECORD": 29,
            "key": ":D:8_0::::#RES",
            "seqnum": 3113,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 30,
            "key": ":U:::::ID_FS_APPLICATION_ID",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 31,
            "key": ":D:8_16::::#MOD",
            "seqnum": 3114,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                "sd"
            ]
        },
        {
            "RECORD": 32,
            "key": ":D:253_4::::#MOD",
            "seqnum": 3112,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                "device_mapper"
            ]
        },
        {
            "RECORD": 33,
            "key": ":D:253_2::::#RES",
            "seqnum": 3105,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 34,
            "key": ":D:253_3::::#RDY",
            "seqnum": 3108,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 35,
            "key": ":D:253_4::::#RDY",
            "seqnum": 3112,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 36,
            "key": ":D:253_1::::#RES",
            "seqnum": 3102,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 37,
            "key": ":D:253_3::::#MOD",
            "seqnum": 3108,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                "device_mapper"
            ]
        },
        {
            "RECORD": 38,
            "key": ":D:8_0:LYR:::#GIN",
            "seqnum": 3101,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:253_0:LYR::",
                ":D:253_1:LYR::"
            ]
        },
        {
            "RECORD": 39,
            "key": ":D:253_0::::#MOD",
            "seqnum": 3099,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                "device_mapper"
            ]
        },
        {
            "RECORD": 40,
            "key": ":U:::::ID_FS_USAGE",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 41,
            "key": ":U:::::ID_FS_UUID",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 42,
            "key": ":D:253_0::::#RDY",
            "seqnum": 3099,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 43,
            "key": ":U:::::ID_FS_TYPE",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 44,
            "key": ":U:::::ID_FS_SYSTEM_ID",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 45,
            "key": ":D:253_3:LYR:::#GIN",
            "seqnum": 3110,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:253_4:LYR::"
            ]
        },
        {
            "RECORD": 46,
            "key": ":D:253_3:LYR:::#GMB",
            "seqnum": 3107,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ":D:8_16:LYR::"
            ]
        },
        {
            "RECORD": 47,
            "key": ":U:::::ID_PART_ENTRY_TYPE",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "block/blkid",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 48,
            "key": ":D:8_0:USR:::SID_NEXT_MOD",
            "seqnum": 3113,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": true},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": false}
            ],
            "owner": "block/blkid",
            "values": [
                "dm"
            ]
        },
        {
            "RECORD": 49,
            "key": ":D:8_0::::#MOD",
            "seqnum": 3113,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                "sd"
            ]
        },
        {
            "RECORD": 50,
            "key": ":U:(null)::::SID_SESSION_ID",
            "seqnum": 0,
            "flags": [
                {"KV_PERSISTENT": true},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": false},
                {"KV_MOD_RESERVED": false}
            ],
            "owner": "#core",
            "values": [
                "25750db7-1554-48f0-a659-d0a6dcb6ab14"
            ]
        },
        {
            "RECORD": 51,
            "key": ":D:8_16::::#RES",
            "seqnum": 3114,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        },
        {
            "RECORD": 52,
            "key": ":D:8_0::::#RDY",
            "seqnum": 3113,
            "flags": [
                {"KV_PERSISTENT": false},
                {"KV_MOD_PROTECTED": false},
                {"KV_MOD_PRIVATE": true},
                {"KV_MOD_RESERVED": true}
            ],
            "owner": "#core",
            "values": [
                ""
            ]
        }
    ]
}
```

**Comment by prajnoha** [comment]
> Note: CI failure was because clang wasn't installed on the Centos Stream systems. That has been fixed.
> 
> The latest push fixed the bug.
> Fixed the clang warnings.
> Updated "flags" to a boolean array.
> "values" is always an array - even if it only has one value.

Ah, this reminds me that we should fix the protocol for the `dump` operation to transmit information about the value being either a single value or a vector value - currently it's all considered vector/array so we can't differentiate.

I wanted to use the same function that exports db diffs from worker processes to main process (`_export_kv_store`) even for the `dump` operation, but I think the fn needs a few edits so it can be reused. Also I wanted to use buffer with memfd backend in the `_export_kv_store` (currently, it uses `memfd` directly).

Anyway, this is a separate issue - I'll open a new one here in GH for this if not already open...

> Validated the JSON with : https://jsonlint.com/
> 

Yup, looks good! Thanks! I'll merge this now and when we have the protocol fixed, we can also add the flag in the dump output making a difference between single and vector values.

**Comment by prajnoha** [comment]
> I wanted to use the same function that exports db diffs from worker processes to main process (`_export_kv_store`) even for the `dump` operation

That is #87.

**Comment by prajnoha** [comment]
There's also #73 which is also related to output - if we come across a binary value, we should be printing it properly (formatted hex dump?) or not printing it at all and instead putting "binary unprintable value" on output in the place of the actual value.

**Pull request merged**
